version: "3"
services:
  db:
    env_file:
      - "./.env"
    container_name: "database"
    image:  postgres
    restart: always 
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
       POSTGRES_PASSWORD: "${DATABASE_PASS}"
    volumes:
      - capricornio_db:/home/database/db

  frontend:
    env_file:
      "./frontend/.env"
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "capricornio-frontend"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    links:
    - "backend"

  backend:
    env_file:
      "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "capricornio-backend"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    links:
    - "db"
volumes:
  capricornio_db:
    external: true